# Generated by Django 4.0.6 on 2022-07-20 12:12

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_remove_user_image_user_birthday_user_cover_picture_and_more'),
        ('tweeter_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='likes',
            new_name='tweet_likes',
        ),
    ]
