# Generated by Django 4.0.6 on 2022-07-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter_api', '0007_remove_tweet_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tweets/images'),
        ),
    ]
