# Generated by Django 4.0.6 on 2022-07-25 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0004_comment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='retweets',
            field=models.ManyToManyField(related_name='retweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
