# Generated by Django 4.0.6 on 2022-07-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_retweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='retweets',
            field=models.ManyToManyField(related_name='retweets', to='comments.comment'),
        ),
    ]
