# Generated by Django 4.0.6 on 2022-07-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_retweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='retweets',
            field=models.ManyToManyField(to='comments.comment'),
        ),
    ]
