# Generated by Django 4.0.6 on 2022-07-29 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0007_alter_comment_retweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='comments_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
