# Generated by Django 4.0.6 on 2022-07-23 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter_api', '0007_remove_tweet_comment'),
        ('comments', '0002_comment_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tweeter_api.tweet'),
            preserve_default=False,
        ),
    ]
