insert into user_user (id, first_name, last_name, email, date_created, bio, date_of_birth, phone, website, password, is_superuser, username, is_staff, is_active, date_joined) values (1, 'Anastasie', 'Alfonsetti', 'apigeram0@salon.com', '2021-09-14', 'nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit', '2021-12-17', '835-110-2809', 'http://unc.edu/nulla/facilisi/cras/non/velit.js', 'b0kRNDKqkp', true, 'Pigeram', true, false, '2022-05-14');
insert into user_user (id, first_name, last_name, email, date_created, bio, date_of_birth, phone, website, password, is_superuser, username, is_staff, is_active, date_joined) values (2, 'Hinze', 'Canfer', 'htottie1@dailymotion.com', '2021-08-24', 'aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices', '2021-10-22', '140-489-5726', 'https://infoseek.co.jp/et/ultrices/posuere.json', '33gCjaZoS', false, 'Tottie', true, true, '2021-10-09');
insert into user_user (id, first_name, last_name, email, date_created, bio, date_of_birth, phone, website, password, is_superuser, username, is_staff, is_active, date_joined) values (3, 'Rayna', 'Ferby', 'rmauchlen2@so-net.ne.jp', '2022-06-22', 'tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus', '2021-11-10', '214-558-4868', 'http://earthlink.net/id/pretium/iaculis/diam/erat/fermentum.json', 'uAY9vI1o', false, 'Mauchlen', false, true, '2021-11-06');
insert into user_user (id, first_name, last_name, email, date_created, bio, date_of_birth, phone, website, password, is_superuser, username, is_staff, is_active, date_joined) values (4, 'Blondy', 'Onge', 'bsebley3@prweb.com', '2021-12-02', 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis', '2021-09-06', '667-127-4213', 'http://tiny.cc/orci/nullam/molestie/nibh.aspx', '3nujMZ0R5s', false, 'Sebley', true, true, '2022-04-16');
insert into user_user (id, first_name, last_name, email, date_created, bio, date_of_birth, phone, website, password, is_superuser, username, is_staff, is_active, date_joined) values (5, 'Aarika', 'Roches', 'avokins4@qq.com', '2021-12-20', 'viverra eget congue eget semper rutrum nulla nunc purus phasellus in', '2022-03-23', '337-347-8010', 'https://nih.gov/dolor/vel/est/donec/odio.jpg', 'Hcy8hbj', false, 'Vokins', true, false, '2022-01-01');
insert into user_user (id, first_name, last_name, email, date_created, bio, date_of_birth, phone, website, password, is_superuser, username, is_staff, is_active, date_joined) values (6, 'Leanor', 'Arunowicz', 'lchasemoore5@wufoo.com', '2022-05-25', 'lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis', '2021-10-20', '988-997-2987', 'http://rediff.com/est/phasellus/sit/amet/erat/nulla/tempus.jpg', 'c0nyBQ', true, 'Chasemoore', false, true, '2021-11-25');
insert into user_user (id, first_name, last_name, email, date_created, bio, date_of_birth, phone, website, password, is_superuser, username, is_staff, is_active, date_joined) values (7, 'Pincus', 'Schlagtmans', 'pfreemantle6@phoca.cz', '2021-09-13', 'molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus', '2022-07-18', '420-432-1086', 'http://tinypic.com/at/turpis/donec/posuere/metus/vitae.html', 'vCyVWcc', false, 'Freemantle', true, true, '2022-03-14');
insert into user_user (id, first_name, last_name, email, date_created, bio, date_of_birth, phone, website, password, is_superuser, username, is_staff, is_active, date_joined) values (8, 'Ame', 'Isakovitch', 'awareing7@jimdo.com', '2022-01-31', 'eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor', '2022-06-06', '333-789-4161', 'https://wikimedia.org/tellus/in/sagittis/dui/vel.jsp', 'LWj8Yulxrzw', true, 'Wareing', false, false, '2022-01-29');
insert into user_user (id, first_name, last_name, email, date_created, bio, date_of_birth, phone, website, password, is_superuser, username, is_staff, is_active, date_joined) values (9, 'Dannel', 'Shemilt', 'dmartensen8@mlb.com', '2021-11-18', 'sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar', '2021-11-05', '646-481-6126', 'https://merriam-webster.com/proin/risus.png', 'n5RGcibRGts', true, 'Martensen', true, false, '2022-03-19');
insert into user_user (id, first_name, last_name, email, date_created, bio, date_of_birth, phone, website, password, is_superuser, username, is_staff, is_active, date_joined) values (10, 'Myra', 'Carlyle', 'mschneidau9@house.gov', '2022-05-10', 'luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in', '2021-11-21', '844-484-8634', 'https://newsvine.com/magnis/dis/parturient/montes/nascetur.jpg', 'WUSIDO1skeW', false, 'Schneidau', false, false, '2022-04-20');



insert into tweeter_api_tweet (id, content, user_id, date_created) values (1, 'neutral', 1, '2021-12-17');
insert into tweeter_api_tweet (id, content, user_id, date_created) values (2, 'Operative', 2, '2022-06-11');
insert into tweeter_api_tweet (id, content, user_id, date_created) values (3, 'Ameliorated', 3, '2022-07-24');
insert into tweeter_api_tweet (id, content, user_id, date_created) values (4, 'Robust', 4, '2021-10-10');
insert into tweeter_api_tweet (id, content, user_id, date_created) values (5, 'needs-based', 5, '2022-02-03');
insert into tweeter_api_tweet (id, content, user_id, date_created) values (6, 'explicit', 6, '2022-05-08');
insert into tweeter_api_tweet (id, content, user_id, date_created) values (7, 'circuit', 7, '2022-05-25');
insert into tweeter_api_tweet (id, content, user_id, date_created) values (8, 'flexibility', 8, '2021-11-04');
insert into tweeter_api_tweet (id, content, user_id, date_created) values (9, 'attitude', 9, '2022-04-01');
insert into tweeter_api_tweet (id, content, user_id, date_created) values (10, 'superstructure', 10, '2021-10-03');
