# Generated by Django 4.0.6 on 2022-07-22 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_delete_comments'),
        ('tweeter_api', '0005_tweetlike_remove_tweet_retweets_tweet_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweet', to='comments.comment'),
        ),
    ]
